### ISSUE TITLE
Problem with the Japanese PS1 Files of Diablo.

### ISSUE THREAD

**Issue by ArthurDM2** [diasurgical/psx-tools#5]
Hello everyone, i'm new here, i'm learning a little bit of codes and i hear the code of Diasurgical of PSX Tools are available here.

The problem is that i'm using the code for extract the Japanese BIN and DIR files of Diablo ( yes i have the files i get has long time).
and i'm trying as i can while i'm extracting but in the folder doesn't anything that mention it.

I read the code of the creator and mentions also needs the japanese files for extract it and if someone can help me with this and i have the original japanese files anyone who wants to have it just ask me,

Please i need that files as bank files one way or the other if someone can ripping them for use.

**Comment by AJenbo** [comment]
Did you build the tools, how are you running them, what errors do you get? This might be useful: https://github.com/diabpsx/divination

**Comment by ArthurDM2** [comment]
> Did you build the tools, how are you running them, what errors do you get? This might be useful: https://github.com/diabpsx/divination

Honestly, i downloaded the code in zip format that you are telling me i think is the same code there but when i execute the batch files for dump the content or extract it does nothing just leave it a empty folder and says dstream.exe is not recognized as an internal o external command. I am doing something wrong? look is that I am new to this and i was interested in ripping and extracting the game's BIN and DIR files.
I need the sound effects from those files but I don't know what I'm doing wrong or i must to execute the code for my own itself? 
Exists a tutorial or something of? I don't want to bother, sorry this is my first time here.

![error00](https://user-images.githubusercontent.com/88517697/128633935-19cbebcb-70fd-48c1-95ea-a0e937f9dda1.png)

**Comment by AJenbo** [comment]
you will need to compile the program first using visual studio

**Comment by ArthurDM2** [comment]
I'm compiling the source code and tooks me off more 5 hours and later i could already except vag2wav doesn't work just i click on the exe and the pop-up cmd window disappears but i'm using other program can read the vag files and can convert into wav files in less of 1 hour but at least works very well as charm. Thanks for help me!

**Comment by AJenbo** [comment]
> vag2wav doesn't work just i click on the exe and the pop-up cmd window disappears

This is how Windows works, you must instead open a CMD window and run vag2wav from there.
