### ISSUE TITLE
wrong double declaration

### ISSUE THREAD

**Issue by MyNameIs-13** [diasurgical/psx-tools#7]
Hello,

the line is causing an error
https://github.com/diasurgical/psx-tools/blob/57ea31cf6259be0be9e476a775524abbb183c146/vag2wav/vag2wav.c#L14

cc -o vag2wav.bin vag2wav/vag2wav.c
vag2wav/vag2wav.c:15:1: error: expected expression before ‘double’
   15 | double f[5][2] = { { 0.0, 0.0 },
      | ^~~~~~
make: *** [Makefile:11: vag2wav.bin] Error 1

Solution:
remove the line

**Comment by AJenbo** [comment]
Could you open a PR instead of an Issue

**Comment by MyNameIs-13** [comment]
I hopefully did now. 
Sorry about that (not familiar enough with git yet)

**Comment by AJenbo** [comment]
thanks
